name: adaptive_learning
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.1.2
  - matplotlib=3.10.3
  - pandas=2.3.0
  - scikit-learn=1.4.2
  - optuna=4.4.0
  - quadprog=0.1.13
  - seaborn=0.13.2
  - ruff=0.12.1
  - wandb=0.21.0
  - pip
  - pip:
      - torch==2.6.0
      - --index-url https://download.pytorch.org/whl/cu126
